version: '3'

tasks:

  up-*:
    vars:
      ENVIRONMENT: '{{index .MATCH 0}}'
    dir: ./ticketo
    cmd: docker compose --env-file .env -f docker-compose-{{.ENVIRONMENT}}.yaml up -d

  down-*:
    vars:
      ENVIRONMENT: '{{index .MATCH 0}}'
    dir: ./ticketo
    cmd: docker compose -f docker-compose-{{.ENVIRONMENT}}.yaml down

  clear-app:
    dir: ./ticketo
    cmds:
      - docker volume rm ticketo_backend_db

  clear-all:
    dir: ./ticketo
    cmds:
      - docker volume rm ticketo_backend_db ticketo_openfga_db ticketo_traefik-logs
      - docker system prune -f
      - docker volume prune -f
      - rm -rf ./letsencrypt
    interactive: true

  sync-compose:
    cmds:
      - git -C ./ticketo pull https://github.com/EventGateFPTU/deployment.git main
